# common
device: "cuda:0"
image_compress_x: 28
image_compress_y: 28
output_class: 10
data_load_workers: 1

# dataset
dataset_do_split: False
dataset_do_split_ratio: 0.7
dataset_train: "./MNIST/train"
dataset_test: "./MNIST/test"

# load ckpt
read_ckpt: "./ckpt/test.ckpt"
symbol_mapping_path: "./ckpt/symbol_mapping.npy"

# train
lr: 0.01
seed: 119908801576900
epoch: 50
batch_size: 4
momentum: 0.9
lr_decay_after_epoch: 10
save_ckpt_folder: "./ckpt"
save_ckpt_name: "test.ckpt"
test_on_train_set_interval: 4
save_ckpt_interval: 4

# test
test_save_path: "./ckpt"

# transfer learning
new_output_class: 16
new_dataset_folder: "./datasets/HASYv2/my"
save_transfer_folder: "./transfer"
save_transfer_ckpt: "./transfer.ckpt"
